### ISSUE TITLE
Traceback when starting swatchbooker

### ISSUE THREAD

**Issue by luyatshimbalanga** [olivierberten/SwatchBooker#11]
Attempting to start swatchbooker using 20170131 snapshot resulted below:
$ swatchbooker 
Traceback (most recent call last):
  File "/usr/lib/swatchbooker/swatchbooker.pyw", line 28, in <module>
    from sbcommon import *
  File "/usr/lib/swatchbooker/sbcommon.py", line 28, in <module>
    from swatchbook import *
  File "/usr/lib/python2.7/site-packages/swatchbook/__init__.py", line 27, in <module>
    from color import *
  File "/usr/lib/python2.7/site-packages/swatchbook/color.py", line 23, in <module>
    from lcms2 import *
  File "/usr/lib/python2.7/site-packages/swatchbook/lcms2.py", line 601, in <module>
    _libs["lcms2"] = load_library("lcms2")
  File "/usr/lib/python2.7/site-packages/swatchbook/lcms2.py", line 350, in load_library
    return self.load(path)
  File "/usr/lib/python2.7/site-packages/swatchbook/lcms2.py", line 366, in load
    raise ImportError(e)
ImportError: /lib/liblcms2.so.2.0.8: wrong ELF class: ELFCLASS32

On Fedora system, here is the listed dependencies:

$ dnf repoquery --requires --resolve swatchbooker
Last metadata expiration check: 2:55:12 ago on Thu Apr 20 17:31:59 2017.
bash-0:4.3.43-4.fc25.x86_64
coreutils-0:8.25-16.fc25.x86_64
coreutils-single-0:8.25-16.fc25.x86_64
python-0:2.7.13-1.fc25.i686
python-0:2.7.13-1.fc25.x86_64
python-libs-0:2.7.13-1.fc25.i686
python-libs-0:2.7.13-1.fc25.x86_64

**Comment by chiddekel** [comment]
I solved this by remove:
Remove sudo dnf remove wine-cms-3.8-1.fc28.i686 ( and dependecy )
Which on system remove i686 version of lcms2-2.9-2.fc28.i686,
and left a lcms2-2.9-2.fc28.x86_64.
( all other depednecy of module SB are place in)
